--[05:00--08:00] ¿í±íÉÏ´« 
SELECT ETL_Job,Description,Last_StartTime,Last_EndTime,Last_JobStatus,Last_TXDate
FROM ODSETL.ETL_JOB    
where 
ETL_SYSTEM in ('BWT') 
and ETL_Job in(
 'T_BWT_DAPD_COMBO_SUM_CNT'
,'T_BWT_DAPD_DIM_MAPPING_OFFER'
,'T_BWT_DAPD_DIM_MAPPING_PD'
,'T_BWT_DAPD_DIM_REGION'
,'T_BWT_DAPD_DIM_SUM_TYPE'
,'T_BWT_DAPD_EVT_TRMNL'
,'T_BWT_DAPD_POINT_MANAGE'
,'T_BWT_DAPD_PRD_ITV_INST'
,'T_BWT_DAPD_PRD_PD_INST'
,'T_BWT_DAPD_PRD_PD_INST_WB'
,'T_BWT_DAPD_PRD_PO_INST'
,'T_BWT_DAPD_PRD_PO_MEMBER'
,'T_BWT_DAPD_PR_BDM_PA'
,'T_BWT_DAPD_PR_BDM_PM'
,'T_BWT_DAPD_PR_BDM_PP'
,'T_BWT_DAPD_PR_BDM_PS'
,'T_BWT_DAPD_PRD_PD_INST_5G'
);
