1日

检查欠费接口25011-25016  >>> 手动放开BBB  >>> 等待触发MONTH_A >>> 放开MONTH_A 下游

--下游作业
SELECT  a.ETL_SYSTEM,a.ETL_JOB,a.Description,a.JobType,a.Enable,a.Last_StartTime,a.Last_EndTime,a.Last_JobStatus,a.Last_TXDate 
FROM  ODSETL.ETL_JOB a
--update odsetl.etl_job a set last_jobstatus = 'Pending',last_txdate = '2016-12-31'
where
a.ETL_SYSTEM not in ('ORC','SYN') 
and a.ETL_JOB in (select Stream_Job from odsetl.ETL_Job_Stream where ETL_Job IN ('T_AWT_PRD_PROD_INST_MONTH_A'))
;

--==DAPM_PRD_REPORT_CLCT_TGT_2(重点指标汇总上报接口（月）_2号)核查流程：填写《集团重点指标宽表指标环比核查流程.xls》
SELECT
201902 AS MONTH_ID,A.PRVNCE_ID,A.LATN_ID,A.KEY_TARGET_CD,A.TARGET_UNIT
,SUM(CASE WHEN A.MONTH_ID=201902 THEN A.TARGET_VALUE END) AS TARGET_VALUE
,SUM(CASE WHEN A.MONTH_ID=TO_CHAR(ADD_MONTHS(TO_DATE('201902','201905'),-1),'201905') THEN A.TARGET_VALUE END) AS TARGET_VALUE_LASTMONTH
FROM ODSPMART.T_BWT_DAPM_PRD_REPORT_CLCTTGT2 A
WHERE A.MONTH_ID>=TO_CHAR(ADD_MONTHS(TO_DATE('201902','201905'),-1),'201905')
AND A.KEY_TARGET_CD IN ('M1010101001','M1010103013','M1010103031','M1010202051','M1010202060','M1010202061','M1010202062')
GROUP BY A.PRVNCE_ID,A.LATN_ID,A.KEY_TARGET_CD,A.TARGET_UNIT
ORDER BY A.KEY_TARGET_CD;

2日

从计费得到14004 14005两个补充数据，将这两个数据补充到已经入的接口数据里，重新跑BOS 和 BBB  59上有load脚本
14004 和 14005两个文件需要修改分隔符，并在最后加入字段，按照3月份的数据标准来做

查看25001-25010  月账 财务月账 核对记录数  放开BBB  

T_MID_FIN_INCOM  跑完后通知张道平调账

调账后 放开下游三个作业  会触发MONTH_B

依据情况放开MONTH_B 下游

--下游作业
SELECT  a.ETL_SYSTEM,a.ETL_JOB,a.Description,a.JobType,a.Enable,a.Last_StartTime,a.Last_EndTime,a.Last_JobStatus,a.Last_TXDate 
FROM  ODSETL.ETL_JOB a
--update odsetl.etl_job a set last_jobstatus = 'Pending',last_txdate = '2016-12-31'
where
a.ETL_SYSTEM not in ('ORC','SYN') 
and a.ETL_JOB in (select Stream_Job from odsetl.ETL_Job_Stream where ETL_Job IN ('T_AWT_PRD_PROD_INST_MONTH_B'))
;


3日

--==DAPM_PRD_REPORT_CLCT_TGT(重点指标汇总上报接口（月）_5号)核查流程：填写《集团重点指标宽表指标环比核查流程.xls》
SELECT * FROM ODSPMART.T_BWT_DAPM_PRD_REPORT_CLCT_TGT A
WHERE A.MONTH_ID=201902
ORDER BY A.KEY_TARGET_CD;

SELECT * FROM ODSPMART.T_BWT_DAPM_PRD_REPORT_CLCT_TGT
WHERE MONTH_ID>=TO_CHAR(ADD_MONTHS(TO_DATE('201902','201905'),-1),'201905')
ORDER BY KEY_TARGET_CD,MONTH_ID;

SELECT * FROM ODSPMART.T_BWT_DAPM_PRD_REPORT_CLCT_TGT A
WHERE A.MONTH_ID=201902
ORDER BY A.KEY_TARGET_CD;

--------------------------------------------------------CPSP 流程 

						14004、14005(陶敏) 21005(刘冬) 先核查
						--==甘肃电信CPSP结算业务收入处理流程==--：

						1：检查作业调度涉及的相关表是否完成分析:
						A:检查表是否分析（涉及的表可以从存储过程中查询，注意替换表的月份）
						SELECT A.OWNER,A.TABLE_NAME,A.NUM_ROWS FROM DBA_TABLES A
						WHERE A.OWNER||'.'||A.TABLE_NAME IN
						(
						'CRMPDATA.T_PRD_PROD_OFFER'
						,'ODSPMART.T_AWT_PRD_PROD_FUNC_A_201905'
						,'ODSPMART.T_AWT_PRD_PROD_INST_201905'
						,'ODSPMART.T_AWT_PRD_PROD_OFFER_201905'
						,'ODSPMART.T_MID_ACCT_ITEM_TOTAL'
						,'ODSPMART.T_MID_FIN_INCOME_201905'
						,'ODSPMART.T_MID_PRD_FUNC_INST_201905'
						,'ODSPMART.T_MID_EVT_ITV_VIEWINFO_201905'
						,'OTHPDATA.T_BIL_ACCT_ITEM'
						,'OTHPDATA.T_BIL_PAID_ACCT_ITEM'
						,'OTHPDATA.T_EVT_EVENT_EXT'
						,'OTHPDATA.T_EVT_EVENT_TGVAS'
						,'OTHPDATA.T_EVT_EVENT_TGVAS_FEE'
						,'OTHPDATA.T_EVT_EVENT_TGCDR'
						,'OTHPDATA.T_FIN_DZQD_IPTV_INCOME'
						,'OTHPDATA.T_FIN_TISS_118114_INCOME'
						,'OTHPDATA.T_JTD_YZF_LHLG_KPI'
						)
						
						B:对未分析的表进行执行手动分析（参照以下语法，注意修改用户和表名称）：
						4	ODSPMART	T_AWT_PRD_PROD_OFFER_201904	
8	ODSPMART	T_MID_PRD_FUNC_INST_201904	
3	ODSPMART	T_MID_FIN_INCOME_201904	
1	ODSPMART	T_AWT_PRD_PROD_FUNC_A_201904	
2	ODSPMART	T_MID_EVT_ITV_VIEWINFO_201904	

						EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME =>'ODSPMART',TABNAME=>'T_MID_FIN_INCOME_201905',ESTIMATE_PERCENT=>50,DEGREE=>32,CASCADE=>TRUE,NO_INVALIDATE=>FALSE);
						EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME =>'ODSPMART',TABNAME=>'T_MID_EVT_ITV_VIEWINFO_201905',ESTIMATE_PERCENT=>50,DEGREE=>32,CASCADE=>TRUE,NO_INVALIDATE=>FALSE);
						EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME =>'ODSPMART',TABNAME=>'T_MID_FIN_INCOME_201904',ESTIMATE_PERCENT=>50,DEGREE=>32,CASCADE=>TRUE,NO_INVALIDATE=>FALSE);
						EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME =>'ODSPMART',TABNAME=>'T_AWT_PRD_PROD_FUNC_A_201904',ESTIMATE_PERCENT=>50,DEGREE=>32,CASCADE=>TRUE,NO_INVALIDATE=>FALSE);
						EXEC DBMS_STATS.GATHER_TABLE_STATS(OWNNAME =>'ODSPMART',TABNAME=>'T_MID_EVT_ITV_VIEWINFO_201904',ESTIMATE_PERCENT=>50,DEGREE=>32,CASCADE=>TRUE,NO_INVALIDATE=>FALSE);
						
						2：数据处理调度：
						[MID] T_MID_CPSP_SETTLE_INDEX
						[FCT] T_FCT_CPSP_SETTLE_INDEX
						
						3：报表数据：
						月报-CPSP结算业务收入-目录下两张报表
						检查指标收入环比是否存在异常并进行核查
						
						4：收入列账系统接口提供作业调度（手动执行）：
						[EXP] EXP_T_DIM_CPSP_SETTLE_INDEX
						[EXP] EXP_T_FCT_CPSP_SETTLE_INDEX
						[EXP] EXP_T_MID_CPSP_SETTLE_INDEX

@@@@实名制上传上传@@@

移动护士站结算规则调整及收入手动干预两个月，CPSP【201903】和【201904】账期需要手动删除以下数据后重新执行FCT，移动护士站此两个账期数据为0。
DELETE FROM ODSPMART.T_MID_CPSP_SETTLE_INDEX A
WHERE A.MONTH_ID>=201903 AND A.MONTH_ID<=201904
AND A.INDEX_CODE='WWHB-103750';
COMMIT;