
SELECT 
CASE WHEN (V.Last_JobStatus IS NULL AND V.DTTIME >V.START_TIME) THEN V.ETL_Job||U.ALARM_L0||v.USERNAME||U.ALARM_ACT||V.PHONE ELSE
     CASE WHEN (V.Last_JobStatus ='Failed')  THEN V.ETL_Job||U.ALARM_L1||v.USERNAME||U.ALARM_ACT||V.PHONE ELSE
          CASE WHEN (V.Last_JobStatus ='Runing'and V.DTTIME>V.END_TIME )  THEN V.ETL_Job||U.ALARM_L2||v.USERNAME||U.ALARM_ACT||V.PHONE END
     END
END

 FROM (
SELECT T.ETL_Job
,Description
,TO_DATE(Last_StartTime,'YYYY-MM-DD HH24:MI:SS') Last_StartTime
,TO_DATE(Last_EndTime,'YYYY-MM-DD HH24:MI:SS') Last_EndTime
,Last_JobStatus
,Last_TXDate
,P.USERNAME
,P.PHONE
,TO_DATE(SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'),1,10)||' '||t.start_time||':00','YYYY-MM-DD HH24:MI:SS') START_TIME
,TO_DATE(SUBSTR(TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'),1,10)||' '||t.End_Time||':00','YYYY-MM-DD HH24:MI:SS') END_TIME
,SYSDATE DTTIME
FROM ODSPMART.T_MON_DIM_KEY_JOB T
LEFT JOIN ODSETL.ETL_JOB K   
ON T.ETL_JOB=K.ETL_JOB
AND K.LAST_TXDATE=SUBSTR(TO_CHAR(SYSDATE-1,'YYYY-MM-DD HH24:MI:SS'),1,10)
LEFT JOIN (
SELECT A.DAY_ID,B.USERNAME,B.PHONE FROM ODSPMART.T_MON_DIM_ROTA A
,ODSPMART.T_MON_DIM_TELEPHONE B
WHERE A.NIGHTSHIFT=B.USERNAME
AND A.DAY_ID =CAST(SUBSTR(TO_CHAR(SYSDATE-1,'YYYYMMDD HH24:MI:SS'),1,8) AS INT)
) P
ON 1=1
WHERE T.ETL_JOB NOT IN (SELECT L.ETL_Job FROM  ODSETL.ETL_JOB L WHERE L.LAST_TXDATE=SUBSTR(TO_CHAR(SYSDATE-1,'YYYY-MM-DD HH24:MI:SS'),1,10) AND L.LAST_JOBSTATUS='Done')
) V
, ODSPMART.T_MON_DIM_ALARM_LEVEL U


--处理告警信息方法
select * from odspmart.t_mon_dim_alarm_del;
insert into odspmart.t_mon_dim_alarm_del values('T_BWT_DAPD_COMBO_SUM_CNT','20200126');
commit;
