--7.集团上传查询
SELECT ETL_Job,Description,Last_StartTime,Last_EndTime,Last_JobStatus,Last_TXDate
FROM ODSETL.ETL_JOB    
where 
ETL_SYSTEM in ('BWT') 
and ETL_Job in(
'EXP_T_BWT_DAPD_COMBO_SUM_CNT'
,'EXP_T_BWT_DAPD_DIM_MAPPING_OFFER'
,'EXP_T_BWT_DAPD_DIM_PO_SPEC'
,'EXP_T_BWT_DAPD_DIM_MAPPING_PD'
,'EXP_T_BWT_DAPD_DIM_REGION'
,'EXP_T_BWT_DAPD_DIM_SUM_TYPE'
,'EXP_T_BWT_DAPD_EVT_TRMNL'
,'EXP_T_BWT_DAPD_POINT_MANAGE'
,'EXP_T_BWT_DAPD_PRD_ITV_INST'
,'EXP_T_BWT_DAPD_PRD_PD_INST'
,'EXP_T_BWT_DAPD_PRD_PD_INST_WB'
,'EXP_T_BWT_DAPD_PRD_PO_INST'
,'EXP_T_BWT_DAPD_PRD_PO_MEMBER'
,'EXP_T_BWT_DAPD_PR_BDM_PA'
,'EXP_T_BWT_DAPD_PR_BDM_PM'
,'EXP_T_BWT_DAPD_PR_BDM_PP'
,'EXP_T_BWT_DAPD_PR_BDM_PS'
,'EXP_T_BWT_DAPD_PRD_PD_INST_5G'
);
